//+------------------------------------------------------------------+
//|                                                 GoldSAR_Pro.mq5   |
//|          Stop-and-Reverse gold scalper (from video) + filters    |
//|                                                                  |
//|  WHAT THIS IS                                                     |
//|  A MetaTrader 5 Expert Advisor that automates the "stop-and-      |
//|  reverse" (SAR) idea seen in the source video: always hold one    |
//|  position, and flip direction when the market turns against it.   |
//|                                                                  |
//|  THE PROFIT MECHANISM (honest version)                            |
//|  You cannot guarantee a net-profitable robot. What you CAN do is  |
//|  build a POSITIVE-EXPECTANCY structure so that, over many trades, |
//|  wins outweigh losses. This EA does that three ways:              |
//|    1) WIN BIG, LOSE SMALL  - take-profit and trailing are set     |
//|       wider than the stop (reward:risk > 1). Then you are net     |
//|       positive even with a sub-50% win rate.                      |
//|    2) ONLY TRADE WHEN IT CAN WORK - a trend/volatility filter     |
//|       (Donchian breakout + ADX strength + EMA direction) keeps    |
//|       the EA OUT of the choppy ranges that bleed this strategy.   |
//|    3) HARD SAFETY RAILS - spread filter, daily-loss cutoff, and   |
//|       an equity stop so one bad run cannot spiral.                |
//|                                                                  |
//|  Expectancy = (WinRate x AvgWin) - (LossRate x AvgLoss).          |
//|  This EA is designed to make AvgWin >> AvgLoss. It is still your  |
//|  job to BACKTEST and DEMO-TEST before ever risking real money.    |
//|                                                                  |
//|  NOT FINANCIAL ADVICE. Trading leveraged gold can lose money fast.|
//+------------------------------------------------------------------+
#property copyright "Generated by Claude Code"
#property version   "1.00"
#property description "Stop-and-reverse gold scalper with trend filter, asymmetric exits and risk caps."

#include <Trade/Trade.mqh>
#include <Trade/PositionInfo.mqh>

//====================== INPUTS ======================================
input group "=== Strategy: Stop-and-Reverse ==="
input ENUM_TIMEFRAMES InpTimeframe   = PERIOD_CURRENT; // Working timeframe (video used M1)
input int    InpBreakoutBars = 20;    // Breakout lookback (bars) - entry/flip trigger
input bool   InpReverseOnOpp = true;  // Flip to opposite side on an opposite breakout (SAR)

input group "=== Trend / regime filter (keeps you out of chop) ==="
input bool   InpUseAdx       = true;  // Require a strong trend (ADX)
input int    InpAdxPeriod    = 14;    // ADX period
input double InpAdxMin       = 22.0;  // Only trade when ADX >= this
input bool   InpUseEma       = true;  // Require EMA trend agreement
input int    InpEmaFast      = 21;    // Fast EMA
input int    InpEmaSlow      = 50;    // Slow EMA

input group "=== Exits: win big, lose small ==="
input int    InpAtrPeriod    = 14;    // ATR period (sizes SL/TP to volatility)
input double InpSL_ATR       = 1.5;   // Stop-loss  = ATR x this
input double InpTP_ATR       = 3.0;   // Take-profit= ATR x this  (keep > SL for +R:R)
input bool   InpUseTrailing  = true;  // Trail the stop to let winners run
input double InpTrailStartATR= 1.0;   // Start trailing after price moves this many ATR in profit
input double InpTrailATR     = 1.5;   // Trailing distance in ATR

input group "=== Money management ==="
input bool   InpUseRiskPct   = false; // true = size by risk %, false = fixed lot
input double InpFixedLot     = 0.01;  // Fixed lot size (video used 0.01)
input double InpRiskPct      = 0.5;   // % of balance risked per trade (if UseRiskPct)

input group "=== Safety rails ==="
input double InpMaxSpread    = 40;    // Max spread in points to allow a trade (0 = off)
input double InpDailyLossPct = 3.0;   // Stop for the day after -X% of day-start equity (0 = off)
input double InpEquityStopPct= 85.0;  // Halt & close if equity < X% of start balance (0 = off)
input int    InpMaxTradesDay = 30;    // Max trades per day (0 = off)

input group "=== General ==="
input long   InpMagic        = 770816;      // Magic number (unique per EA/chart)
input int    InpSlippage     = 30;          // Max deviation (points)
input string InpComment      = "GoldSAR_Pro";

//====================== GLOBALS =====================================
CTrade         trade;
CPositionInfo  pos;

int  hAtr  = INVALID_HANDLE;
int  hAdx  = INVALID_HANDLE;
int  hEmaF = INVALID_HANDLE;
int  hEmaS = INVALID_HANDLE;

ENUM_TIMEFRAMES g_tf;
datetime g_lastBar        = 0;
datetime g_day            = 0;
double   g_dayStartEquity = 0.0;
double   g_initialBalance = 0.0;
int      g_tradesToday    = 0;
bool     g_haltedToday    = false;
bool     g_haltedEquity   = false;

//+------------------------------------------------------------------+
int OnInit()
{
   g_tf = (InpTimeframe == PERIOD_CURRENT) ? (ENUM_TIMEFRAMES)_Period : InpTimeframe;

   // --- basic sanity on inputs
   if(InpTP_ATR <= InpSL_ATR)
      Print("WARNING: TP_ATR (",InpTP_ATR,") <= SL_ATR (",InpSL_ATR,
            "). Reward:risk is <= 1 - the +expectancy edge is weakened.");

   // --- indicator handles
   hAtr  = iATR(_Symbol, g_tf, InpAtrPeriod);
   hAdx  = iADX(_Symbol, g_tf, InpAdxPeriod);
   hEmaF = iMA(_Symbol, g_tf, InpEmaFast, 0, MODE_EMA, PRICE_CLOSE);
   hEmaS = iMA(_Symbol, g_tf, InpEmaSlow, 0, MODE_EMA, PRICE_CLOSE);

   if(hAtr==INVALID_HANDLE || hAdx==INVALID_HANDLE || hEmaF==INVALID_HANDLE || hEmaS==INVALID_HANDLE)
   {
      Print("Failed to create indicator handles.");
      return(INIT_FAILED);
   }

   trade.SetExpertMagicNumber(InpMagic);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetTypeFillingBySymbol(_Symbol);

   g_initialBalance = AccountInfoDouble(ACCOUNT_BALANCE);
   ResetDay();

   Print("GoldSAR_Pro initialised on ",_Symbol," ",EnumToString(g_tf),
         " | SL=",InpSL_ATR,"ATR  TP=",InpTP_ATR,"ATR  (R:R ",
         DoubleToString(InpTP_ATR/InpSL_ATR,2),":1)");
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   if(hAtr !=INVALID_HANDLE) IndicatorRelease(hAtr);
   if(hAdx !=INVALID_HANDLE) IndicatorRelease(hAdx);
   if(hEmaF!=INVALID_HANDLE) IndicatorRelease(hEmaF);
   if(hEmaS!=INVALID_HANDLE) IndicatorRelease(hEmaS);
}

//+------------------------------------------------------------------+
void OnTick()
{
   // need enough history for the lookbacks
   if(Bars(_Symbol, g_tf) < InpBreakoutBars + InpEmaSlow + 10)
      return;

   RollDay();          // reset daily counters at a new day
   CheckRiskHalts();   // equity stop + daily-loss cutoff (may close all)

   if(g_haltedEquity)  // permanent halt until EA is reattached
      return;

   ManageTrailing();   // trail the stop every tick

   if(!IsNewBar())     // signals are evaluated once per closed bar
      return;

   int sig = Signal(); // +1 long, -1 short, 0 no trade

   if(HasPos())
   {
      int dir = (pos.PositionType()==POSITION_TYPE_BUY) ? +1 : -1;

      // Stop-and-reverse: opposite breakout flips the position
      if(InpReverseOnOpp && sig!=0 && sig!=dir)
      {
         CloseAll();
         if(RiskAllowsNewTrade() && SpreadOK())
            OpenTrade(sig);
      }
   }
   else
   {
      if(sig!=0 && RiskAllowsNewTrade() && SpreadOK())
         OpenTrade(sig);
   }
}

//====================== SIGNAL ======================================
// Donchian breakout of the last InpBreakoutBars, confirmed by ADX
// strength and EMA trend direction. Returns +1 / -1 / 0.
int Signal()
{
   double c1 = iClose(_Symbol, g_tf, 1);              // last closed bar
   double hh = HighestHigh(2, InpBreakoutBars);       // prior N-bar high
   double ll = LowestLow (2, InpBreakoutBars);        // prior N-bar low
   if(hh<=0 || ll<=0 || c1<=0)
      return 0;

   int sig = 0;
   if(c1 > hh) sig = +1;
   else if(c1 < ll) sig = -1;
   if(sig==0) return 0;

   // --- ADX: is the move strong enough to be worth riding?
   if(InpUseAdx)
   {
      double adx = BufVal(hAdx, 0, 1);
      if(adx < InpAdxMin) return 0;
   }

   // --- EMA: only trade breakouts that agree with the trend
   if(InpUseEma)
   {
      double ef = BufVal(hEmaF, 0, 1);
      double es = BufVal(hEmaS, 0, 1);
      if(ef==0 || es==0) return 0;
      int emaDir = (ef > es) ? +1 : -1;
      if(emaDir != sig) return 0;
   }

   return sig;
}

//====================== ORDER HELPERS ===============================
void OpenTrade(int dir)
{
   double atr = ATR();
   if(atr <= 0) return;

   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double price = (dir>0) ? ask : bid;

   double slDist = InpSL_ATR * atr;
   double tpDist = InpTP_ATR * atr;

   // respect the broker's minimum stop distance
   double minDist = (double)SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;
   if(slDist < minDist) slDist = minDist;
   if(tpDist < minDist) tpDist = minDist;

   double sl = (dir>0) ? price - slDist : price + slDist;
   double tp = (dir>0) ? price + tpDist : price - tpDist;
   sl = NormalizeDouble(sl, _Digits);
   tp = NormalizeDouble(tp, _Digits);

   double lots = CalcLots(slDist);
   if(lots <= 0) return;

   bool ok = (dir>0) ? trade.Buy (lots, _Symbol, price, sl, tp, InpComment)
                     : trade.Sell(lots, _Symbol, price, sl, tp, InpComment);
   if(ok) g_tradesToday++;
}

void CloseAll()
{
   if(HasPos())
      trade.PositionClose(_Symbol);
}

bool HasPos()
{
   return (pos.Select(_Symbol) && pos.Magic()==InpMagic);
}

// Trail the stop once the trade is InpTrailStartATR in profit, keeping
// it InpTrailATR behind price. This is what lets winners run.
void ManageTrailing()
{
   if(!InpUseTrailing) return;
   if(!HasPos())       return;

   double atr = ATR();
   if(atr <= 0) return;

   int    dir   = (pos.PositionType()==POSITION_TYPE_BUY) ? +1 : -1;
   double open  = pos.PriceOpen();
   double curSL = pos.StopLoss();
   double curTP = pos.TakeProfit();
   double price = (dir>0) ? SymbolInfoDouble(_Symbol, SYMBOL_BID)
                          : SymbolInfoDouble(_Symbol, SYMBOL_ASK);

   double moved = (dir>0) ? (price-open) : (open-price);
   if(moved < InpTrailStartATR * atr) return;

   double newSL = (dir>0) ? price - InpTrailATR*atr : price + InpTrailATR*atr;
   newSL = NormalizeDouble(newSL, _Digits);

   double minDist = (double)SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;

   if(dir>0)
   {
      if((curSL==0.0 || newSL>curSL) && (price-newSL) >= minDist)
         trade.PositionModify(_Symbol, newSL, curTP);
   }
   else
   {
      if((curSL==0.0 || newSL<curSL) && (newSL-price) >= minDist)
         trade.PositionModify(_Symbol, newSL, curTP);
   }
}

//====================== MONEY MANAGEMENT ============================
double CalcLots(double slDist)
{
   if(!InpUseRiskPct)
      return NormalizeLot(InpFixedLot);

   double riskMoney = AccountInfoDouble(ACCOUNT_BALANCE) * InpRiskPct / 100.0;
   double tickVal   = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickSize<=0 || tickVal<=0 || slDist<=0)
      return NormalizeLot(InpFixedLot);

   double lossPerLot = (slDist / tickSize) * tickVal;   // loss for 1.0 lot at SL
   if(lossPerLot <= 0)
      return NormalizeLot(InpFixedLot);

   return NormalizeLot(riskMoney / lossPerLot);
}

double NormalizeLot(double lot)
{
   double mn = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double mx = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double st = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   if(st<=0) st = 0.01;

   lot = MathFloor(lot/st) * st;
   if(lot < mn) lot = mn;
   if(lot > mx) lot = mx;

   int lotDigits = (int)MathRound(-MathLog10(st));
   if(lotDigits < 0) lotDigits = 0;
   return NormalizeDouble(lot, lotDigits);
}

//====================== RISK RAILS ==================================
void CheckRiskHalts()
{
   double eq = AccountInfoDouble(ACCOUNT_EQUITY);

   // hard equity stop (measured from EA start balance)
   if(InpEquityStopPct>0 && g_initialBalance>0 &&
      eq < g_initialBalance * InpEquityStopPct/100.0)
   {
      if(HasPos()) CloseAll();
      if(!g_haltedEquity)
         Print("EQUITY STOP hit at ",DoubleToString(eq,2),". Trading halted until reattach.");
      g_haltedEquity = true;
   }

   // daily loss cutoff (measured from day-start equity)
   if(InpDailyLossPct>0 && g_dayStartEquity>0 &&
      eq <= g_dayStartEquity * (1.0 - InpDailyLossPct/100.0))
   {
      if(HasPos()) CloseAll();
      if(!g_haltedToday)
         Print("DAILY LOSS limit hit. No new trades until tomorrow.");
      g_haltedToday = true;
   }
}

bool RiskAllowsNewTrade()
{
   if(g_haltedEquity) return false;
   if(g_haltedToday)  return false;
   if(InpMaxTradesDay>0 && g_tradesToday>=InpMaxTradesDay) return false;
   return true;
}

bool SpreadOK()
{
   if(InpMaxSpread<=0) return true;
   double spread = (SymbolInfoDouble(_Symbol,SYMBOL_ASK) -
                    SymbolInfoDouble(_Symbol,SYMBOL_BID)) / _Point;
   return (spread <= InpMaxSpread);
}

//====================== UTILITIES ===================================
bool IsNewBar()
{
   datetime t = iTime(_Symbol, g_tf, 0);
   if(t != g_lastBar) { g_lastBar = t; return true; }
   return false;
}

void RollDay()
{
   datetime cur = TimeCurrent();
   datetime dayStart = cur - (cur % 86400);
   if(dayStart != g_day)
      ResetDay();
}

void ResetDay()
{
   g_day            = TimeCurrent() - (TimeCurrent() % 86400);
   g_dayStartEquity = AccountInfoDouble(ACCOUNT_EQUITY);
   g_tradesToday    = 0;
   g_haltedToday    = false;
}

double ATR() { return BufVal(hAtr, 0, 1); }

// read one indicator buffer value at a given shift
double BufVal(int handle, int buffer, int shift)
{
   double b[];
   if(CopyBuffer(handle, buffer, shift, 1, b) == 1)
      return b[0];
   return 0.0;
}

double HighestHigh(int start, int count)
{
   int idx = iHighest(_Symbol, g_tf, MODE_HIGH, count, start);
   if(idx < 0) return 0.0;
   return iHigh(_Symbol, g_tf, idx);
}

double LowestLow(int start, int count)
{
   int idx = iLowest(_Symbol, g_tf, MODE_LOW, count, start);
   if(idx < 0) return 0.0;
   return iLow(_Symbol, g_tf, idx);
}
//+------------------------------------------------------------------+
